// <auto-generated />
using System;
using EduPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929200723_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduPortal.Models.Entities.Achievements", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("ConditionEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.Property<int>("CourseScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseScheduleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CourseLocationTypesLocationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyDuration")
                        .HasColumnType("int");

                    b.HasKey("CourseScheduleId");

                    b.HasIndex("CourseLocationTypesLocationTypeId");

                    b.HasIndex("CoursesCourseId");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseScheduleAttributes", b =>
                {
                    b.Property<int>("CourseScheduleAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseScheduleAttributeId"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekDayId")
                        .HasColumnType("int");

                    b.Property<int>("WeekDaysWeekDayId")
                        .HasColumnType("int");

                    b.Property<int>("activityTypesActivityTypeId")
                        .HasColumnType("int");

                    b.HasKey("CourseScheduleAttributeId");

                    b.HasIndex("CourseScheduleId");

                    b.HasIndex("WeekDaysWeekDayId");

                    b.HasIndex("activityTypesActivityTypeId");

                    b.ToTable("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CourseCategoriesCourseCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TitleEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCategoriesCourseCategoryId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Enrollments", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CoursesCourseId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamResults", b =>
                {
                    b.Property<int>("ExamResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResultId"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypesExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Lecturer")
                        .HasColumnType("int");

                    b.Property<float>("ResultScore")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("ExamResultId");

                    b.HasIndex("ExamScheduleId");

                    b.HasIndex("ExamTypesExamTypeId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("ExamScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamScheduleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("CourseLocationTypesLocationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("int");

                    b.Property<int>("EndDate")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypesExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Lecturer")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("ExamScheduleId");

                    b.HasIndex("CourseLocationTypesLocationTypeId");

                    b.HasIndex("CoursesCourseId");

                    b.HasIndex("ExamTypesExamTypeId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("ExamSchedule");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExceptionLogs", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inf_ErrorCodesCode")
                        .HasColumnType("int");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("Inf_ErrorCodesCode");

                    b.HasIndex("UsersUserId");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ActivityTypes", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("Inf_ActivityTypes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseCategories", b =>
                {
                    b.Property<int>("CourseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CourseCategoryId");

                    b.ToTable("Inf_CourseCategories");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseLocationTypes", b =>
                {
                    b.Property<int>("LocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("LocationTypeId");

                    b.ToTable("Inf_CourseLocationTypes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ErrorCodes", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("Inf_ErrorCodes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ExamTypes", b =>
                {
                    b.Property<int>("ExamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ExamTypeId");

                    b.ToTable("Inf_ExamTypes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_NotificationTypes", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("Inf_NotificationTypes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_RestrictionLevels", b =>
                {
                    b.Property<int>("RestrictionLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestrictionLevelId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RestrictionLevelId");

                    b.ToTable("Inf_RestrictionLevels");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_UserStatuses", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("StatusId");

                    b.ToTable("Inf_UserStatuses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_Weekdays", b =>
                {
                    b.Property<int>("WeekDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekDayId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeekDayId");

                    b.ToTable("Inf_Weekdays");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Notifications", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypesNotificationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypesNotificationTypeId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserAchievements", b =>
                {
                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAchievementId"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<int>("AchievementsAchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementsAchievementId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserTokens", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("JwtId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RewokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersSessionsUserSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("UsersSessionsUserSessionId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Inf_UserStatusesStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockedUntill")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Inf_UserStatusesStatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersRoles", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RolesRoleId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.Property<int>("UserSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSessionId"));

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("Inf_RestrictionLevelsRestrictionLevelId")
                        .HasColumnType("int");

                    b.Property<string>("IpAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestrictionLevelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime2");

                    b.HasKey("UserSessionId");

                    b.HasIndex("Inf_RestrictionLevelsRestrictionLevelId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_CourseLocationTypes", "CourseLocationTypes")
                        .WithMany("CourseSchedules")
                        .HasForeignKey("CourseLocationTypesLocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Courses", "Courses")
                        .WithMany("CourseSchedules")
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLocationTypes");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseScheduleAttributes", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.CourseSchedule", "CourseSchedule")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("CourseScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_Weekdays", "WeekDays")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("WeekDaysWeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_ActivityTypes", "activityTypes")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("activityTypesActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseSchedule");

                    b.Navigation("WeekDays");

                    b.Navigation("activityTypes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_CourseCategories", "CourseCategories")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoriesCourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("Course")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Enrollments", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Courses", "Courses")
                        .WithMany("Enrollments")
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("Enrollments")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamResults", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.ExamSchedule", "ExamSchedules")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_ExamTypes", "ExamTypes")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamTypesExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSchedules");

                    b.Navigation("ExamTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_CourseLocationTypes", "CourseLocationTypes")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("CourseLocationTypesLocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Courses", "Courses")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_ExamTypes", "ExamTypes")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("ExamTypesExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLocationTypes");

                    b.Navigation("Courses");

                    b.Navigation("ExamTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExceptionLogs", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_ErrorCodes", "Inf_ErrorCodes")
                        .WithMany("ExceptionLogs")
                        .HasForeignKey("Inf_ErrorCodesCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("ExceptionLogs")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inf_ErrorCodes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Notifications", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_NotificationTypes", "NotificationTypes")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypesNotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserAchievements", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Achievements", "Achievements")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementsAchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievements");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserTokens", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.UsersSessions", "UsersSessions")
                        .WithMany("UserTokens")
                        .HasForeignKey("UsersSessionsUserSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("UserTokens")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");

                    b.Navigation("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_UserStatuses", "Inf_UserStatuses")
                        .WithMany("Users")
                        .HasForeignKey("Inf_UserStatusesStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inf_UserStatuses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersRoles", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Roles", "Roles")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_RestrictionLevels", "Inf_RestrictionLevels")
                        .WithMany("UsersSessions")
                        .HasForeignKey("Inf_RestrictionLevelsRestrictionLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Users")
                        .WithMany("UsersSessions")
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inf_RestrictionLevels");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Achievements", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.Navigation("CourseSchedules");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ActivityTypes", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseCategories", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseLocationTypes", b =>
                {
                    b.Navigation("CourseSchedules");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ErrorCodes", b =>
                {
                    b.Navigation("ExceptionLogs");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ExamTypes", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_NotificationTypes", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_RestrictionLevels", b =>
                {
                    b.Navigation("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_UserStatuses", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_Weekdays", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Roles", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamSchedules");

                    b.Navigation("ExceptionLogs");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserTokens");

                    b.Navigation("UsersRoles");

                    b.Navigation("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
