// <auto-generated />
using System;
using EduPortal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPortal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251120130525_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduPortal.Models.Entities.Achievements", b =>
                {
                    b.Property<int>("AchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementId"));

                    b.Property<string>("ConditionEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AchievementId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.Property<int>("CourseScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseScheduleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeeklyDuration")
                        .HasColumnType("int");

                    b.HasKey("CourseScheduleId");

                    b.HasIndex("CourseId");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("CourseSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseScheduleAttributes", b =>
                {
                    b.Property<int>("CourseScheduleAttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseScheduleAttributeId"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CourseScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekDayId")
                        .HasColumnType("int");

                    b.HasKey("CourseScheduleAttributeId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("CourseScheduleId");

                    b.HasIndex("WeekDayId");

                    b.ToTable("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("CourseCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TitleEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCategoryId");

                    b.HasIndex("CreatorId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerification");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Enrollments", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamResults", b =>
                {
                    b.Property<int>("ExamResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamResultId"));

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Lecturer")
                        .HasColumnType("int");

                    b.Property<float>("ResultScore")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ExamResultId");

                    b.HasIndex("ExamScheduleId");

                    b.HasIndex("ExamTypeId");

                    b.HasIndex("Lecturer");

                    b.ToTable("ExamResults");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.Property<int>("ExamScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamScheduleId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("EndDate")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Lecturer")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StartDate")
                        .HasColumnType("int");

                    b.HasKey("ExamScheduleId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExamTypeId");

                    b.HasIndex("Lecturer");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("ExamSchedule");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExceptionLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("UserId");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ActivityTypes", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityTypeId");

                    b.ToTable("Inf_ActivityTypes");

                    b.HasData(
                        new
                        {
                            ActivityTypeId = 1,
                            DescrEng = "Lecture",
                            DescrLocal = "ლექცია"
                        },
                        new
                        {
                            ActivityTypeId = 2,
                            DescrEng = "Working Group",
                            DescrLocal = "სემინარი"
                        },
                        new
                        {
                            ActivityTypeId = 3,
                            DescrEng = "Practicum",
                            DescrLocal = "პრაქტიკული"
                        },
                        new
                        {
                            ActivityTypeId = 4,
                            DescrEng = "Lab",
                            DescrLocal = "ლაბორატორიული"
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseCategories", b =>
                {
                    b.Property<int>("CourseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseCategoryId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CourseCategoryId");

                    b.ToTable("Inf_CourseCategories");

                    b.HasData(
                        new
                        {
                            CourseCategoryId = 1,
                            Code = "CS",
                            DescrEng = "Computer Science",
                            DescrLocal = "კომპიუტერული მეცნიერება",
                            IsActive = true
                        },
                        new
                        {
                            CourseCategoryId = 2,
                            Code = "MaTh",
                            DescrEng = "Mathematics",
                            DescrLocal = "მათემატიკა",
                            IsActive = true
                        },
                        new
                        {
                            CourseCategoryId = 3,
                            Code = "SC",
                            DescrEng = "Natural Science",
                            DescrLocal = "საბუნებისმეტყველო მეცნიერება",
                            IsActive = true
                        },
                        new
                        {
                            CourseCategoryId = 4,
                            Code = "GE",
                            DescrEng = "General Education",
                            DescrLocal = "ზოგადი განათლება",
                            IsActive = true
                        },
                        new
                        {
                            CourseCategoryId = 5,
                            Code = "Free",
                            DescrEng = "Free Credits",
                            DescrLocal = "თავისუფალი კრედიტები",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseLocationTypes", b =>
                {
                    b.Property<int>("LocationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("LocationTypeId");

                    b.ToTable("Inf_CourseLocationTypes");

                    b.HasData(
                        new
                        {
                            LocationTypeId = 1,
                            DescrEng = "On Site",
                            DescrLocal = "ადგილზე",
                            IsActive = true
                        },
                        new
                        {
                            LocationTypeId = 2,
                            DescrEng = "Online",
                            DescrLocal = "ონლაინ",
                            IsActive = true
                        },
                        new
                        {
                            LocationTypeId = 3,
                            DescrEng = "Hybrid",
                            DescrLocal = "ჰიბრიდული",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ErrorCodes", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("Inf_ErrorCodes");

                    b.HasData(
                        new
                        {
                            Code = "0000",
                            DescrEng = "Unknown error",
                            DescrLocal = "უცნობი შეცდომა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1000",
                            DescrEng = "Invalid parameter in the function",
                            DescrLocal = "არასწორი პარამეტრი ფუნქციაში",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1001",
                            DescrEng = "Data not found",
                            DescrLocal = "მონაცემები ვერ მოიძებნა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1002",
                            DescrEng = "Invalid input data",
                            DescrLocal = "არასწორი შეყვანილი მონაცემები",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1003",
                            DescrEng = "User not found",
                            DescrLocal = "მომხმარებელი ვერ მოიძებნა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1004",
                            DescrEng = "Invalid password",
                            DescrLocal = "პაროლი არასწორია",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1005",
                            DescrEng = "Access denied",
                            DescrLocal = "წვდომა აკრძალულია",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1006",
                            DescrEng = "Session expired",
                            DescrLocal = "სესია დასრულებულია",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1007",
                            DescrEng = "Unauthorized request",
                            DescrLocal = "მოთხოვნა არ არის ავტორიზებული",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1008",
                            DescrEng = "Data processing failed",
                            DescrLocal = "მონაცემების დამუშავება ვერ მოხერხდა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1009",
                            DescrEng = "Server temporarily unavailable",
                            DescrLocal = "სერვერი დროებით მიუწვდომელია",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1010",
                            DescrEng = "Course not found",
                            DescrLocal = "კურსი ვერ მოიძებნა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1011",
                            DescrEng = "Exam not found",
                            DescrLocal = "გამოცდა ვერ მოიძებნა",
                            IsActive = true
                        },
                        new
                        {
                            Code = "1012",
                            DescrEng = "User already registered",
                            DescrLocal = "მომხმარებელს უკვე აქვს რეგისტრაცია",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ExamTypes", b =>
                {
                    b.Property<int>("ExamTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ExamTypeId");

                    b.ToTable("Inf_ExamTypes");

                    b.HasData(
                        new
                        {
                            ExamTypeId = 1,
                            DescrEng = "Quiz",
                            DescrLocal = "ქვიზი",
                            IsActive = true
                        },
                        new
                        {
                            ExamTypeId = 2,
                            DescrEng = "Midterm",
                            DescrLocal = "შუალედური",
                            IsActive = true
                        },
                        new
                        {
                            ExamTypeId = 3,
                            DescrEng = "Final Exam",
                            DescrLocal = "ფინალური გამოცდა",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_NotificationTypes", b =>
                {
                    b.Property<int>("NotificationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationTypeId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("NotificationTypeId");

                    b.ToTable("Inf_NotificationTypes");

                    b.HasData(
                        new
                        {
                            NotificationTypeId = 1,
                            DescrEng = "New course added",
                            DescrLocal = "ახალი კურსი დამატებულია",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 2,
                            DescrEng = "Exam reminder",
                            DescrLocal = "გამოცდის დრო ახლოვდება",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 3,
                            DescrEng = "New announcement",
                            DescrLocal = "ახალი განცხადება/შეტყობინება",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 4,
                            DescrEng = "New course material",
                            DescrLocal = "კურსში ახალი მასალა აიტვირთა",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 5,
                            DescrEng = "Grade published",
                            DescrLocal = "შეფასება გამოქვეყნდა",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 6,
                            DescrEng = "New message received",
                            DescrLocal = "ახალი შეტყობინება მიღებულია",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 7,
                            DescrEng = "Assignment due reminder",
                            DescrLocal = "დავალების ვადა ახლოვდება",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 8,
                            DescrEng = "Verification pin code",
                            DescrLocal = "ვერიფიკაციის პინ კოდი",
                            IsActive = true
                        },
                        new
                        {
                            NotificationTypeId = 9,
                            DescrEng = "Your account is locked",
                            DescrLocal = "თქვენი ანგარიში დაილოქა",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_RestrictionLevels", b =>
                {
                    b.Property<int>("RestrictionLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestrictionLevelId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RestrictionLevelId");

                    b.ToTable("Inf_RestrictionLevels");

                    b.HasData(
                        new
                        {
                            RestrictionLevelId = 1,
                            DescrEng = "Test Mode",
                            DescrLocal = "სატესტო რეჟიმი",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_UserStatuses", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("StatusId");

                    b.ToTable("Inf_UserStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            DescrEng = "Active",
                            DescrLocal = "აქტიური",
                            IsActive = true
                        },
                        new
                        {
                            StatusId = 2,
                            DescrEng = "Inactive",
                            DescrLocal = "არაქტიური",
                            IsActive = true
                        },
                        new
                        {
                            StatusId = 3,
                            DescrEng = "Suspended",
                            DescrLocal = "შეჩერებული",
                            IsActive = true
                        },
                        new
                        {
                            StatusId = 4,
                            DescrEng = "Blocked",
                            DescrLocal = "დაბლოკილი",
                            IsActive = true
                        },
                        new
                        {
                            StatusId = 5,
                            DescrEng = "Unverified",
                            DescrLocal = "დაუდასტურებელი",
                            IsActive = true
                        },
                        new
                        {
                            StatusId = 6,
                            DescrEng = "Deleted",
                            DescrLocal = "წაშლილი",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_Weekdays", b =>
                {
                    b.Property<int>("WeekDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeekDayId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeekDayId");

                    b.ToTable("Inf_Weekdays");

                    b.HasData(
                        new
                        {
                            WeekDayId = 1,
                            DescrEng = "Monday",
                            DescrLocal = "ორშაბათი"
                        },
                        new
                        {
                            WeekDayId = 2,
                            DescrEng = "Tuesday",
                            DescrLocal = "სამშაბათი"
                        },
                        new
                        {
                            WeekDayId = 3,
                            DescrEng = "Wednesday",
                            DescrLocal = "ოთხშაბათი"
                        },
                        new
                        {
                            WeekDayId = 4,
                            DescrEng = "Thursday",
                            DescrLocal = "ხუთშაბათი"
                        },
                        new
                        {
                            WeekDayId = 5,
                            DescrEng = "Friday",
                            DescrLocal = "პარასკევი"
                        },
                        new
                        {
                            WeekDayId = 6,
                            DescrEng = "Saturday",
                            DescrLocal = "შაბათი"
                        },
                        new
                        {
                            WeekDayId = 7,
                            DescrEng = "Sunday",
                            DescrLocal = "კვირა"
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Notifications", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("DescrEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescrLocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            DescrEng = "Student",
                            DescrLocal = "სტუდენტი",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            DescrEng = "Lecturer",
                            DescrLocal = "ლექტორი",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            DescrEng = "Admin",
                            DescrLocal = "ადმინისტრატორი",
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 4,
                            DescrEng = "SuperAdmin",
                            DescrLocal = "სუპერ ადმინისტრატორი",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserAchievements", b =>
                {
                    b.Property<int>("UserAchievementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAchievementId"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserAchievementId");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserTokens", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAttempt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockedUntill")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginFailCounter")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersRoles", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersRoles");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.Property<int>("UserSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSessionId"));

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAdress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestrictionLevelId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidTill")
                        .HasColumnType("datetime2");

                    b.HasKey("UserSessionId");

                    b.HasIndex("RestrictionLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Courses", "Course")
                        .WithMany("CourseSchedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_CourseLocationTypes", "LocationType")
                        .WithMany("CourseSchedules")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseScheduleAttributes", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_ActivityTypes", "Activity")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.CourseSchedule", "Schedule")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("CourseScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_Weekdays", "WeekDay")
                        .WithMany("CourseScheduleAttributes")
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Schedule");

                    b.Navigation("WeekDay");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_CourseCategories", "Categories")
                        .WithMany("Courses")
                        .HasForeignKey("CourseCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "Creator")
                        .WithMany("Course")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.EmailVerification", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("EmailVerifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Enrollments", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Courses", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamResults", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.ExamSchedule", "Schedule")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_ExamTypes", "ExamType")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("Lecturer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamType");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Courses", "Course")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_ExamTypes", "ExamType")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("Lecturer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Inf_CourseLocationTypes", "CourseLocationType")
                        .WithMany("ExamSchedules")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CourseLocationType");

                    b.Navigation("ExamType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExceptionLogs", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_ErrorCodes", "ErrorCode")
                        .WithMany("ExceptionLogs")
                        .HasForeignKey("Code");

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("ExceptionLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("ErrorCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Notifications", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_NotificationTypes", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserAchievements", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Achievements", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("UserAchievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UserTokens", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.UsersSessions", "Session")
                        .WithMany("UserTokens")
                        .HasForeignKey("SessionId");

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_UserStatuses", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersRoles", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Roles", "Role")
                        .WithMany("UsersRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("UsersRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.HasOne("EduPortal.Models.Entities.Inf_RestrictionLevels", "RestrictionLevel")
                        .WithMany("UsersSessions")
                        .HasForeignKey("RestrictionLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPortal.Models.Entities.Users", "User")
                        .WithMany("UsersSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestrictionLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Achievements", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.CourseSchedule", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Courses", b =>
                {
                    b.Navigation("CourseSchedules");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.ExamSchedule", b =>
                {
                    b.Navigation("ExamResults");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ActivityTypes", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseCategories", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_CourseLocationTypes", b =>
                {
                    b.Navigation("CourseSchedules");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ErrorCodes", b =>
                {
                    b.Navigation("ExceptionLogs");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_ExamTypes", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("ExamSchedules");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_NotificationTypes", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_RestrictionLevels", b =>
                {
                    b.Navigation("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_UserStatuses", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Inf_Weekdays", b =>
                {
                    b.Navigation("CourseScheduleAttributes");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Roles", b =>
                {
                    b.Navigation("UsersRoles");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.Users", b =>
                {
                    b.Navigation("Course");

                    b.Navigation("EmailVerifications");

                    b.Navigation("Enrollments");

                    b.Navigation("ExamSchedules");

                    b.Navigation("ExceptionLogs");

                    b.Navigation("UserAchievements");

                    b.Navigation("UserTokens");

                    b.Navigation("UsersRoles");

                    b.Navigation("UsersSessions");
                });

            modelBuilder.Entity("EduPortal.Models.Entities.UsersSessions", b =>
                {
                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
